# Part 1: Create Your Own Dataset

## Objective
In this section, we create a custom dataset using a Python dictionary.  
The dataset contains 5 features and 15 rows with a custom index.

## Approach
- Define a dictionary with student-related data
- Assign a custom index
- Convert it into a pandas DataFrame

In [7]:
# Part 1: Create Custom Dataset

import pandas as pd

data = {
    "Name": ["Student"+str(i) for i in range(1,16)],
    "Age": [18,19,20,21,22,18,19,20,21,22,18,19,20,21,22],
    "Study_Hours": [2,3,4,5,6,3,4,5,6,7,2,3,4,5,6],
    "Sleep_Hours": [6,7,8,5,6,7,6,5,8,7,6,7,8,5,6],
    "Score": [50,55,60,65,70,58,62,66,72,75,54,59,63,68,73]
}

index_labels = ["S"+str(i) for i in range(1,16)]

df_custom = pd.DataFrame(data, index=index_labels)

df_custom

          Name  Age  Study_Hours  Sleep_Hours  Score
S1    Student1   18            2            6     50
S2    Student2   19            3            7     55
S3    Student3   20            4            8     60
S4    Student4   21            5            5     65
S5    Student5   22            6            6     70
S6    Student6   18            3            7     58
S7    Student7   19            4            6     62
S8    Student8   20            5            5     66
S9    Student9   21            6            8     72
S10  Student10   22            7            7     75
S11  Student11   18            2            6     54
S12  Student12   19            3            7     59
S13  Student13   20            4            8     63
S14  Student14   21            5            5     68
S15  Student15   22            6            6     73

# Part 2: Titanic Dataset Analysis

## Step 1: Data Exploration

## Objective
Understand the structure and summary of the dataset.

## Methods Used
- `.head()` to preview data
- `.info()` to inspect structure and missing values
- `.describe()` to view statistical summary

In [8]:
from google.colab import files
uploaded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset (1).csv

In [9]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Step 2: Data Cleaning

## Objective
Handle missing values and remove unnecessary data.

## Actions Taken
- Fill missing values in Age using median
- Fill missing values in Embarked using mode
- Drop Cabin column due to many missing values
- Remove duplicate rows

In [10]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df.drop("Cabin", axis=1, inplace=True)
df.drop_duplicates(inplace=True)

## Step 3: Data Analysis

## Objective
Analyze survival patterns using groupby operations.

## Analysis Performed
- Survival rate by gender
- Survival rate by passenger class
- Average age per class
- Survival rate by age group

In [11]:
# Survival by gender
df.groupby("Sex")["Survived"].mean()

# Survival by class
df.groupby("Pclass")["Survived"].mean()

# Average age per class
df.groupby("Pclass")["Age"].mean()

# Create age groups
df["AgeGroup"] = pd.cut(df["Age"], bins=[0,12,18,35,60,100],
                       labels=["Child","Teen","Young Adult","Adult","Senior"])

# Survival by age group
df.groupby("AgeGroup")["Survived"].mean()

/tmp/ipykernel_5919/2838587158.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("AgeGroup")["Survived"].mean()

AgeGroup
Child          0.579710
Teen           0.428571
Young Adult    0.353271
Adult          0.400000
Senior         0.227273
Name: Survived, dtype: float64

## Step 4: Data Filtering

## Objective
Extract specific groups of passengers for deeper insights.

## Filters Applied
- Female passengers who survived
- Children who survived
- First-class passengers who survived

In [12]:
# Female survivors
df[(df["Sex"] == "female") & (df["Survived"] == 1)]

# Children survivors
df[(df["Age"] < 12) & (df["Survived"] == 1)]

# First class survivors
df[(df["Pclass"] == 1) & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Young Adult
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,Adult
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S,Young Adult
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28.0,1,0,PC 17569,146.5208,C,Young Adult
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,S,Adult
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,S,Adult
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Young Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Young Adult

## Step 5: Insights

## Key Findings

- Females had a significantly higher survival rate than males.
- Passenger class strongly influenced survival chances, with 1st class having the highest survival rate.
- Children showed relatively higher survival rates, supporting the "women and children first" principle.
- The highest survival probability was observed among female passengers in 1st class.